<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_firstname</name>
   <tag></tag>
   <elementGuidId>9416fb39-11ba-4b64-a882-8213838b721f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstname</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^([^0-9๐-๙_@.#$=!%^)(\]:\*;\?\/\,}{'\|&lt;>\[&amp;\+\-\\\u0022]*)$</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Firstname</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-touched ng-dirty ng-invalid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/my-app[1]/app-edit-profile[1]/div[@class=&quot;container-fluid centurygothic-font&quot;]/form[@class=&quot;ng-touched ng-dirty ng-invalid&quot;]/div[@class=&quot;row w3-margin-top&quot;]/div[@class=&quot;col-xs-12 col-sm-6 col-sm-offset-3&quot;]/div[@class=&quot;w3-card w3-margin-top w3-margin-bottom&quot;]/div[@class=&quot;w3-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-9 w3-padding-16 formuser&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-9 w3-padding-large&quot;]/div[1]/input[@class=&quot;ng-touched ng-dirty ng-invalid&quot;]</value>
   </webElementProperties>
</WebElementEntity>
